version: '3.8'
services:
  catalog-service:
    build: ./catalog
    volumes:
      - ./catalog/catalog.csv:/app/catalog.csv
    container_name: catalog-app
    ports:
      - "4567:4567"
  catalog-service-2:
    build: ./catalog
    container_name: catalog-app-2
    ports:
      - "4568:4567"
  order-service:
    build: ./order
    volumes:
      - ./order/orders.csv:/app/orders.csv
    container_name: order-app
    ports:
      - "8081:8081"
    depends_on:
      - catalog-service
  order-service-2:
    build: ./order
    container_name: order-app-2
    ports:
      - "8082:8081"
  frontend-service:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "8080:8080"
    depends_on:
      - catalog-service
      - order-service